1. Import the numpy package under the name np

In [2]:
import numpy as np

2. Print the numpy version and the configuration

3. Create a null vector of size 10 

In [4]:
zero = np.zeros(10)
zero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

4. How to find the memory size of any array

6. Create a null vector of size 10 but the fifth value which is 1 

In [18]:
zero = np. zeros(10)
zero

zero[4] = 1
print(zero)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7. Create a vector with values ranging from 10 to 49

In [23]:
A = np. arange(10,50)
print(A)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


8. Reverse a vector (first element becomes last)

In [24]:
A = np. arange(50)
A = A[::-1]
A

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

 10. Find indices of non-zero elements from [1,2,0,0,4,0]

11. Create a 3x3 identity matrix

In [28]:
Z = np.eye(3)
Z

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

12. Create a 3x3x3 array with random values

In [30]:
Z = np.random.rand(3, 3, 3)
Z

array([[[0.77815139, 0.30584367, 0.20358964],
        [0.78610338, 0.5401342 , 0.53677309],
        [0.17063433, 0.18925951, 0.14705483]],

       [[0.92083756, 0.64032962, 0.58851658],
        [0.56709064, 0.78998457, 0.64787136],
        [0.26842439, 0.65429023, 0.64048372]],

       [[0.12196929, 0.92466921, 0.92088133],
        [0.17114295, 0.70887443, 0.65928907],
        [0.56610554, 0.93267402, 0.91260919]]])

13. Create a 10x10 array with random values and find the minimum and maximum values

In [32]:
A = np. random.rand(10, 10)
Amin, Amax = A.min(), A.max()
Amin, Amax 

(0.0010101866617009403, 0.9968271856334826)

14. Create a random vector of size 30 and find the mean value

In [36]:
A = np.random.rand(30)
Mean = A.mean()
Mean

0.5234338260476002

 15. Create a 2d array with 1 on the border and 0 inside 

In [62]:
A = np.ones((5,5))
A[1:-1,1:-1] = 0
print(A)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


16.How to add a border (filled with 0's) around an existing array? 

In [69]:
A = np.ones((5,5))
A[:,[0,-1]] = 0
A[[0,-1], :] = 0
print(A)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


17. What is the result of the following expression? 
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

19. Create a 8x8 matrix and fill it with a checkerboard pattern